### ISSUE TITLE
Completely empty document doesn't return correctly

### ISSUE THREAD

**Issue by vmx** [pipedown/noise#22]
If you insert a completely empty document then `return .` doesn't return its `_id` field.

This really happens only for a completely empty document, I've also tested documents without `_id` and a single field and documents with an `_id` only.

Test cases are available at pipedown/node-noise#5.

**Comment by Damienkatz** [comment]
Fixed in 65c0bd9c05e3d8c5b144073c2376e86c0fbe341f before I saw this bug report.
