### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by vmx** [pipedown/noise#58]
This repository really needs proper continuous integration. The tests should be run before every commit (possible also the node binding test suite).

**Comment by atd-schubert** [comment]
Maybe I can help you with that...

**Comment by vmx** [comment]
Sure, Travis is fine. Whatever works :)

**Comment by atd-schubert** [comment]
@vmx FYI: You have to activate this repo on https://travis-ci.org/. Otherwise the CI will not work...

**Comment by vmx** [comment]
@atd-schubert Thanks for the information, it looks like it works now (https://github.com/pipedown/noise/pull/57).
